kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: ${DockerRegistry}/${DRONE_REPO}
      registry: ${DockerRegistry}
      insecure: true
      mirror: "https://gecwf5gs.mirror.aliyuncs.com"
      tags:
        - latest
        - ${DRONE_COMMIT}
node:
  env: act